name: CI

on:
  push:
    tags:
      - 'v*' # example: v1.0.0-ksql / v1.0.0

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: |
          VERSION=$(echo $GITHUB_REF_NAME | cut -sd'-' -f1)
          echo "VERSION=${VERSION:-$GITHUB_REF_NAME}" >> $GITHUB_ENV
          CONTEXT=$(echo $GITHUB_REF_NAME | cut -sd'-' -f2)
          echo "CONTEXT=${CONTEXT:-.}" >> $GITHUB_ENV
          NAME_SUFFIX=$(echo $GITHUB_REF_NAME | cut -sd'-' -f2)
          echo "NAME_SUFFIX=${NAME_SUFFIX:-server}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ github.repository }}-${{ env.NAME_SUFFIX }}:${{ env.VERSION }}
          cache-from: type=registry,ref=${{ github.repository }}-${{ env.NAME_SUFFIX }}:buildcache
          cache-to: type=registry,ref=${{ github.repository }}-${{ env.NAME_SUFFIX }}:buildcache,mode=max
